spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.10:8848
        username: nacos
        password: nacos
      gateway: 
        discovery:
          locator:
            enabled: false #不再需要Gateway路由转发
          routes:  #路由规则配置
            #第一个路由配置，service-a路由规则
          - id: service_a_route #路由唯一标识
              #lb开头代表基于gateway的负载均衡策略选择实例
            uri: lb://service-a
              #谓词配置
            predicates:
                #Path路径谓词，代表用户端URI如果以/a开头便会转发到service-a实例
                - Path=/a/**
                #After生效时间谓词，2020年10月15日后该路由才能在网关对外暴露
                - After=2020-10-05T00:00:00.000+08:00[Asia/Shanghai]
              #谓词配置
            filters:
                #忽略掉第一层前缀进行转发
              - StripPrefix=1
                #为响应头附加X-Response=Blue
              - AddResponseHeader=X-Response,Blue
            #第二个路由配置，service-b路由规则
          - id: service_b_route
            uri: lb://service-b
            predicates:
                - Path=/b/**
            filters:
                - StripPrefix=1
server:
  port: 80
management:
  endpoints:
    web:
      exposure:
        include: '*'